[Homework #17] - Class-and-functional-components by Brisa Rojas
qaprosoft/react-laba-arg-1 pull request #176
Opened 2022-09-11 15:10 UTC by bytheseaside

Hey Ilya! Here's my homework 17. 
I'm sorry about the delay

Let me know if I have to change something

2022-09-13 11:31 UTC, ilya-ischenko reviewed
It looks good to me.

I have some suggestions how to improve it:

1. Add loading state when add new tile button was clicked. Network connection can be slow and loading takes time, so user should have UI feedback what's going on.

2. Refresh icon on tile should rotate only when image is loading. I mean when you hover on tile, refresh icon will be static, then after click it will be rotating while image will be fetching

3.Add cursor pointer for add new tile button.

4. Add loading state for refresh all functionality

5. Create "components" folder and move dedicated components to this folder, it will be more flexible and easier to manage it

6. Add try/catch functionality. You can just add "alert" message to notify user that image was not fetched

This improvements is on your own, let me know your decision

2022-09-13 14:05 UTC, bytheseaside commented
Hi Ilya, I'll work on your suggestions

2022-09-14 00:19 UTC, bytheseaside commented
I implemented the loading modifications, but I'm having trouble with the catching error part. Could you give me any suggestions for it? I commited and pushed the code so you can check it

2022-09-14 07:45 UTC, ilya-ischenko requested changes
Looks good in overall, but need to fix some issues:

1.[ Read this one](https://en.reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous), please. Pay attention where you use this.state in setState and fix it according to documentation.

2. Components file should start from upper case letter and be in CamelCase, in this way we can emphasize that this files are components 

One tip: if you want to return object with help of arrow function, you can use this one: `() => ({ key: value })` instead of `() => { return { key: value } }`

2022-09-14 08:03 UTC, ilya-ischenko commented on homeworks/brisa-rojas/17-class-and-functional-components/src/App.js
> +    onLoadAvatar[avatarId] = true;
Do not you change this.state.avatarLoading directly???

2022-09-14 08:03 UTC, ilya-ischenko commented on homeworks/brisa-rojas/17-class-and-functional-components/src/App.js
> +    onLoadAvatar[avatarId] = false;
Do not you change this.state.avatarLoading directly???

2022-09-14 08:03 UTC, ilya-ischenko commented on homeworks/brisa-rojas/17-class-and-functional-components/src/components/avatar-tile.js
> +  }
Unless constructor

2022-09-16 08:47 UTC, ilya-ischenko approved these changes
Well done!
Approved.

2022-09-16 08:48 UTC, merged