[Homework #16] - React Basics by David Azuaje
qaprosoft/react-laba-arg-1 pull request #197
Opened 2022-09-23 04:16 UTC by dazuaje

Hey Mike!

Here is the submission of homework 16#, let me know if it's OK.

2022-09-28 11:08 UTC, solvd-mmelnyk requested changes
Please see my notes!

2022-09-28 11:08 UTC, solvd-mmelnyk commented on homeworks/david-azuaje/16-react-basics/script.js
> +        setColor(0);
it is not good idea to set state directly in render
better approach to have some if condition inside `useEffect`
for example:
```
    React.useEffect(() => {
        setInterval(() => {
            setColor((prevColor) => {
              if(prevColor === 3) {
                return 0
              }
              return prevColor + 1;
            });
        }, 1500);
    }, []);
```

2022-09-28 11:08 UTC, solvd-mmelnyk commented on homeworks/david-azuaje/16-react-basics/script.js
> +            setColor((colors) => colors + 1);
`colors` is not good name for this value. You named it `colors` just because `color` already exist
it is better to use `prevColor`

2022-09-28 19:54 UTC, dazuaje commented on homeworks/david-azuaje/16-react-basics/script.js
> +        setColor(0);
Got it, Thank you Mike. I already fixed it

2022-09-28 19:55 UTC, dazuaje commented on homeworks/david-azuaje/16-react-basics/script.js
> +            setColor((colors) => colors + 1);
Done!

2022-10-05 10:10 UTC, solvd-mmelnyk approved these changes

2022-10-05 10:10 UTC, solvd-mmelnyk approved these changes

2022-10-05 10:10 UTC, merged