[Homework #20] - Routing-redux by Nicolás Roberto
qaprosoft/react-laba-arg-1 pull request #204
Opened 2022-09-26 17:33 UTC by nicolasroberto

2022-09-28 10:54 UTC, solvd-mmelnyk requested changes
Please check my notes!

2022-09-28 10:54 UTC, solvd-mmelnyk commented on homeworks/nicolas-roberto/20-routing-redux/react-router-tutorial/package.json
> +    "react-dom": "^18.2.0"
I see that you use next packages in project:
1. react-router-dom
2. localforage
3. match-sorter
4. sort-by
but I don't see them in `package.json` file

Could you please double-check?

2022-09-28 10:54 UTC, solvd-mmelnyk commented on homeworks/nicolas-roberto/20-routing-redux/redux-toolkit/src/App.jsx
> +  const [todo, setTodo] = useState('');
You used just state
I don't see using Redux Toolkit to handle state.
https://redux-toolkit.js.org/

2022-09-29 02:09 UTC, nicolasroberto commented on homeworks/nicolas-roberto/20-routing-redux/react-router-tutorial/package.json
> +    "react-dom": "^18.2.0"
Thanks, i think i fixed it!

2022-10-05 09:54 UTC, solvd-mmelnyk approved these changes
Good Work!

2022-10-05 09:54 UTC, merged