[homework #6] - js basics 1 by Nicolás Roberto
qaprosoft/react-laba-arg-1 pull request #70
Opened 2022-07-26 03:38 UTC by nicolasroberto

Hey Misha, i'm having trouble with katas 5, 13, 14, 16 and 17.

2022-08-03 15:41 UTC, solvd-mmelnyk requested changes
Please make sure that you correctly use let and const
What problems did you have with katas 5, 13, 14, 16, and 17? did you try to ask in chat others students or me?

2022-08-03 15:41 UTC, solvd-mmelnyk commented on homeworks/nicolas-roberto/06-js-basics-1/main.js
> +  let dayPrice = 40;
please use `const` instead of `let` here
as I see dayPrice value is not changed, and it is constant

2022-08-03 15:41 UTC, solvd-mmelnyk commented on homeworks/nicolas-roberto/06-js-basics-1/main.js
> +  let middleIndex = s.length / 2;
please use `const` instead of `let` here

2022-08-03 15:41 UTC, solvd-mmelnyk commented on package.json
> +  "devDependencies": {
why did you change package.json package-lock.json file?

2022-08-03 15:41 UTC, solvd-mmelnyk commented on homeworks/nicolas-roberto/06-js-basics-1/main.js
> +  let a1Length = a1.length;
please use `const` if value is not changed

2022-08-03 15:41 UTC, solvd-mmelnyk commented on homeworks/nicolas-roberto/06-js-basics-1/main.js
> +  mexicanWave = [];
where is `let` or `const`?

2022-08-03 18:00 UTC, nicolasroberto commented on package.json
> +  "devDependencies": {
> Please make sure that you correctly use let and const What problems did you have with katas 5, 13, 14, 16, and 17? did you try to ask in chat others students or me?

Hey Misha, I kept working in with the other tasks from the latests lectures. I have to try again, i think i should be able to solve some of them now that i being reviewing the material and the videos.
That json changes i think they applied when i reinstalled prettier with the terminal (npm install prettier -D --save-exact) because it wasn't formatting my code.

2022-08-03 18:01 UTC, nicolasroberto commented on homeworks/nicolas-roberto/06-js-basics-1/main.js
> +  mexicanWave = [];
Oh i missed it, i'm going to fix all those "let" now. Thanks for the review

2022-08-11 12:10 UTC, solvd-mmelnyk approved these changes

2022-08-11 12:53 UTC, merged